services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards/spring-boot.json:/etc/grafana/provisioning/dashboards/spring-boot.json
    depends_on:
      - prometheus
    networks:
      - observability

networks:
  observability:
    driver: bridge
