global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tracking-logistico'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['tracking-logistico-api.onrender.com']
    basic_auth:
      username: ''
      password: ''
